/* keysyms.c: UI keysym to Fuse input layer keysym mappings
   Copyright (c) 2000-2007 Philip Kendall, Matan Ziv-Av, Russell Marks
                           Fredrick Meunier, Catalin Mihaila, Stuart Brady

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License along
   with this program; if not, write to the Free Software Foundation, Inc.,
   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

   Author contact information:

   E-mail: philip-fuse@shadowmagic.org.uk

*/

/* This file is autogenerated from keysyms.dat by keysyms.pl.
   Do not edit unless you know what you're doing! */

#include <config.h>


#include "input.h"
#include "keyboard.h"

#include <gdk/gdkkeysyms.h>

keysyms_map_t keysyms_map[] = {

  { GDK_Tab,         INPUT_KEY_Tab         },
  { GDK_Return,      INPUT_KEY_Return      },
  { GDK_Escape,      INPUT_KEY_Escape      },
  { GDK_space,       INPUT_KEY_space       },
  { GDK_numbersign,  INPUT_KEY_numbersign  },
  { GDK_apostrophe,  INPUT_KEY_apostrophe  },
  { GDK_comma,       INPUT_KEY_comma       },
  { GDK_minus,       INPUT_KEY_minus       },
  { GDK_period,      INPUT_KEY_period      },
  { GDK_slash,       INPUT_KEY_slash       },
  { GDK_0,           INPUT_KEY_0           },
  { GDK_1,           INPUT_KEY_1           },
  { GDK_2,           INPUT_KEY_2           },
  { GDK_3,           INPUT_KEY_3           },
  { GDK_4,           INPUT_KEY_4           },
  { GDK_5,           INPUT_KEY_5           },
  { GDK_6,           INPUT_KEY_6           },
  { GDK_7,           INPUT_KEY_7           },
  { GDK_8,           INPUT_KEY_8           },
  { GDK_9,           INPUT_KEY_9           },
  { GDK_semicolon,   INPUT_KEY_semicolon   },
  { GDK_equal,       INPUT_KEY_equal       },
  { GDK_A,           INPUT_KEY_A           },
  { GDK_B,           INPUT_KEY_B           },
  { GDK_C,           INPUT_KEY_C           },
  { GDK_D,           INPUT_KEY_D           },
  { GDK_E,           INPUT_KEY_E           },
  { GDK_F,           INPUT_KEY_F           },
  { GDK_G,           INPUT_KEY_G           },
  { GDK_H,           INPUT_KEY_H           },
  { GDK_I,           INPUT_KEY_I           },
  { GDK_J,           INPUT_KEY_J           },
  { GDK_K,           INPUT_KEY_K           },
  { GDK_L,           INPUT_KEY_L           },
  { GDK_M,           INPUT_KEY_M           },
  { GDK_N,           INPUT_KEY_N           },
  { GDK_O,           INPUT_KEY_O           },
  { GDK_P,           INPUT_KEY_P           },
  { GDK_Q,           INPUT_KEY_Q           },
  { GDK_R,           INPUT_KEY_R           },
  { GDK_S,           INPUT_KEY_S           },
  { GDK_T,           INPUT_KEY_T           },
  { GDK_U,           INPUT_KEY_U           },
  { GDK_V,           INPUT_KEY_V           },
  { GDK_W,           INPUT_KEY_W           },
  { GDK_X,           INPUT_KEY_X           },
  { GDK_Y,           INPUT_KEY_Y           },
  { GDK_Z,           INPUT_KEY_Z           },
  { GDK_a,           INPUT_KEY_a           },
  { GDK_b,           INPUT_KEY_b           },
  { GDK_c,           INPUT_KEY_c           },
  { GDK_d,           INPUT_KEY_d           },
  { GDK_e,           INPUT_KEY_e           },
  { GDK_f,           INPUT_KEY_f           },
  { GDK_g,           INPUT_KEY_g           },
  { GDK_h,           INPUT_KEY_h           },
  { GDK_i,           INPUT_KEY_i           },
  { GDK_j,           INPUT_KEY_j           },
  { GDK_k,           INPUT_KEY_k           },
  { GDK_l,           INPUT_KEY_l           },
  { GDK_m,           INPUT_KEY_m           },
  { GDK_n,           INPUT_KEY_n           },
  { GDK_o,           INPUT_KEY_o           },
  { GDK_p,           INPUT_KEY_p           },
  { GDK_q,           INPUT_KEY_q           },
  { GDK_r,           INPUT_KEY_r           },
  { GDK_s,           INPUT_KEY_s           },
  { GDK_t,           INPUT_KEY_t           },
  { GDK_u,           INPUT_KEY_u           },
  { GDK_v,           INPUT_KEY_v           },
  { GDK_w,           INPUT_KEY_w           },
  { GDK_x,           INPUT_KEY_x           },
  { GDK_y,           INPUT_KEY_y           },
  { GDK_z,           INPUT_KEY_z           },
  { GDK_BackSpace,   INPUT_KEY_BackSpace   },
  { GDK_Up,          INPUT_KEY_Up          },
  { GDK_Down,        INPUT_KEY_Down        },
  { GDK_Left,        INPUT_KEY_Left        },
  { GDK_Right,       INPUT_KEY_Right       },
  { GDK_Insert,      INPUT_KEY_Insert      },
  { GDK_Delete,      INPUT_KEY_Delete      },
  { GDK_Home,        INPUT_KEY_Home        },
  { GDK_End,         INPUT_KEY_End         },
  { GDK_Page_Up,     INPUT_KEY_Page_Up     },
  { GDK_Page_Down,   INPUT_KEY_Page_Down   },
  { GDK_Caps_Lock,   INPUT_KEY_Caps_Lock   },
  { GDK_F1,          INPUT_KEY_F1          },
  { GDK_F2,          INPUT_KEY_F2          },
  { GDK_F3,          INPUT_KEY_F3          },
  { GDK_F4,          INPUT_KEY_F4          },
  { GDK_F5,          INPUT_KEY_F5          },
  { GDK_F6,          INPUT_KEY_F6          },
  { GDK_F7,          INPUT_KEY_F7          },
  { GDK_F8,          INPUT_KEY_F8          },
  { GDK_F9,          INPUT_KEY_F9          },
  { GDK_F10,         INPUT_KEY_F10         },
  { GDK_F11,         INPUT_KEY_F11         },
  { GDK_F12,         INPUT_KEY_F12         },
  { GDK_Shift_L,     INPUT_KEY_Shift_L     },
  { GDK_Shift_R,     INPUT_KEY_Shift_R     },
  { GDK_Control_L,   INPUT_KEY_Control_L   },
  { GDK_Control_R,   INPUT_KEY_Control_R   },
  { GDK_Alt_L,       INPUT_KEY_Alt_L       },
  { GDK_Alt_R,       INPUT_KEY_Alt_R       },
  { GDK_Meta_L,      INPUT_KEY_Meta_L      },
  { GDK_Meta_R,      INPUT_KEY_Meta_R      },
  { GDK_Super_L,     INPUT_KEY_Super_L     },
  { GDK_Super_R,     INPUT_KEY_Super_R     },
  { GDK_Hyper_L,     INPUT_KEY_Hyper_L     },
  { GDK_Hyper_R,     INPUT_KEY_Hyper_R     },
  { GDK_Mode_switch, INPUT_KEY_Mode_switch },

  { 0, 0 }			/* End marker: DO NOT MOVE! */

};

